### ISSUE TITLE
Verification of RPNA_URDF_Example

### ISSUE THREAD

**Issue by BrightAlex** [ROAM-Lab-ND/spatial_v2_extended#11]
Hi, Professor Patrick, 

It seems that the Minimal_Basis and the Perp_Basis matrices obtained from ["RPNA_URDF_Examples.m"](https://github.com/BrightAlex/spatial_v2_extended/blob/dev-RPNA_URDF_test/v3/identifiability/RPNA_URDF_Example.m) do not match with those obtained from ["RPNA_Examples.m"](https://github.com/BrightAlex/spatial_v2_extended/blob/dev-RPNA_URDF_test/v3/identifiability/RPNA_Examples.m). 

I created a new branch  [dev-RPNA_URDF_test](https://github.com/BrightAlex/spatial_v2_extended/tree/dev-RPNA_URDF_test) with the following updates: 
1) A panda URDF with dynamic parameters therein named "panda_arm_no_fixed" was provided;
2) A ["Panda_model()"](https://github.com/BrightAlex/spatial_v2_extended/tree/dev-RPNA_URDF_test/v3/models) function to create a spatial v2 model from modified DH parameters from official website was provided;
3) The  Panda_model() is used in RPNA_Examples.m  to generate Minimal_Basis and Perp_Basis, which were saved in the file ["panda_basis_from_DH"](https://github.com/BrightAlex/spatial_v2_extended/blob/dev-RPNA_URDF_test/v3/models/panda_basis_from_DH.mat);
4) The "panda_arm_no_fixed.urdf" is used in RPNA_URDF_Examples to generate Minimal_Basis and Perp_Basis，which were saved in the file ["panda_basis_from_URDF.mat"](https://github.com/BrightAlex/spatial_v2_extended/blob/dev-RPNA_URDF_test/v3/models/panda_basis_from_URDF.mat) ;
5) An m filie ["UnitTest_Identifiability_Basis"](https://github.com/BrightAlex/spatial_v2_extended/tree/dev-RPNA_URDF_test/v3/unit_tests) was added to verify the result of the RPNA_Examples.m and RPNA_URDF_Examples.m.

![image](https://github.com/user-attachments/assets/b2e1cd4a-51f8-49ea-b4ca-28e00de621f0)
As illustrated in the above code block from  ["UnitTest_Identifiability_Basis"](https://github.com/BrightAlex/spatial_v2_extended/tree/dev-RPNA_URDF_test/v3/unit_tests), the tau6 using the basis matrices from the original RPNA_Examples works well, while the tau7 using the result from RPNA_URDF_Examples.m is not equal to tau1.

Thanks a lot! 
 
Best wishes, 
Yuejiang.

**Comment by pwensing** [comment]
Very interesting. Thanks for documenting this issue so clearly. Have you looked at the models themselves? I would presume that the conversion from URDF to spatial_v2 is good if the inverse dynamics check is passing.

This makes me think the issue is in the URDF precision, such that certain null space calculations in the RPNA are poorly conditioned and returning unexpected results. My suspicion specifically is that the values of pi/2 might not be stored to adequate precision in the URDF. Can you give that a try? If it doesn’t fix the issue, I can dig further to see if there is a bug somewhere. If the URDF precision is the issue, I’d expect a different number of columns in the basis matrices for the DH vs URDF results.

**Comment by pwensing** [comment]
In case my suggested fix doesn't work, for me to take a closer look, I'd ask that you provide the `panda_arm_no_fixed` URDF.

**Comment by pwensing** [comment]
There are several spots in the code where there are numerical thresholds that you may try to adjust as well. 

For example:
https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/de50aab423388d4b21ba1d6cf5d753caab129977/v3/identifiability/SupportFunctions/CleanMat.m#L5

Rref calcs in:
https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/de50aab423388d4b21ba1d6cf5d753caab129977/v3/identifiability/Algorithms/ComputeBases.m#L4

Rank calculation in:
https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/de50aab423388d4b21ba1d6cf5d753caab129977/v3/identifiability/SupportFunctions/RangeBasis.m#L21

**Comment by pwensing** [comment]
Alright, I think I found the issue! Implemented in fbfd46653aedd6436d415c6c0bee842766e85f42

I was missing an RREF computation in `RPNA_URDF_Example.m` and, as a result, its `Perp_Basis` was not consistent with the one from `RPNA_Examples.m`. Here's the specific fix:
https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/fbfd46653aedd6436d415c6c0bee842766e85f42/v3/identifiability/RPNA_URDF_Example.m#L16

Without that step, `Perp_Basis` was a perfectly valid basis for the identifiable parameters. However, the RREF step is necessary for the basis to be used for projection onto the minimal parameters in the way you were using it here:
https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/fbfd46653aedd6436d415c6c0bee842766e85f42/v3/unit_tests/UnitTest_Identifiability_Basis.m#L70

Please close the issue if this change fixes it for you!

**Comment by BrightAlex** [comment]
Sorry for the delay, 
Thank you for your patient review.

Somehow, I missed the panda_arm_no_fixed.urdf, very sorry for that. I uploaded again.
And I checked the precision of the pi/2 in panda_arm_no_fixed.urdf, its `1.57079632679`, which I think is enough.

I tried to add 
` Perp_Basis = rref(Perp_Basis')';` in RPNA_URDF_Example.m as shown below
![image](https://github.com/user-attachments/assets/4176106e-de39-47d4-b764-af295902f6ba)
Unfortunately, then the test still failed as shown below
![image](https://github.com/user-attachments/assets/420e9781-49bc-4884-9d9d-94741d4cbe4b)

**Comment by pwensing** [comment]
Hmm -- I'm not sure what the mix-up is.

I created a new unit test on `main` just to be sure: https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/e54050fce7f99c11790315f78661d974863c98f6/v3/unit_tests/UnitTest_Identifiability_Basis_via_load.m

This one passes for me without issue. 
```
===============================================
ID with model from DH 	 5.241705e-11
ID with model from URDF 	 5.241786e-11
Torque of model from DH 	 5.241769e-11
Torque of model from DH with basis 	 5.241695e-11
Torque of model from URDF 	 5.241675e-11
Torque of model from URDF with basis 	 5.241460e-11
```

Can you pull this down as a clean copy and attempt to verify the operation that way? Otherwise, please provide a link to a commit on your fork so that I might attempt to reproduce the error.

**Comment by BrightAlex** [comment]
Hi Professor, 
I think I have passed the test too! Thank you very much!!
 
![image](https://github.com/user-attachments/assets/0e3168f2-15d7-4bc5-bb8d-5f9e04880f56)

**Comment by BrightAlex** [comment]
This is the link of dev_RPNA_URDF_tets branch on my fork, where I passed the test

https://github.com/BrightAlex/spatial_v2_extended/blob/dev-RPNA_URDF_test/v3/unit_tests/UnitTest_Identifiability_Basis.m
