### ISSUE TITLE
LMI Constraints for Physical Consistency

### ISSUE THREAD

**Issue by Cfather** [ROAM-Lab-ND/spatial_v2_extended#13]
Hi, @pwensing, I have read your [paper](https://ieeexplore.ieee.org/document/7987066) on formulating linear matrix inequalities to ensure physical consistency on inertial parameters. I wonder if there will be similar support in `spatial_v2_extended`, so that we can get computational access to this constraint (for the inertial parameters of each rigid link of the robot). Thanks!

**Comment by pwensing** [comment]
Confirmed! You can find some example code here: https://github.com/ROAM-Lab-ND/inertia_identification_minimal_examples
