### ISSUE TITLE
More Details on Rotor Model

### ISSUE THREAD

**Issue by Cfather** [ROAM-Lab-ND/spatial_v2_extended#14]
Hi, May I ask for more details on the definition of the "rotor model" in spatial_v2_extended?
My understanding is that the rotor model mainly handles the friction on the rotor, which contributes a lot to the system dynamics. I was using the simple motor model in MuJoCo, where parameters like "friction loss, damping, armature inertia" are considered. To be more specific, the motor generates a resistant force that is equal to
$$
friction_loss * sign(v) + dampign * v + armature * a
$$
I assume that the rotor model here is a more generalized model that describes more than a linear relationship. But I'm not sure if I understand this correctly. Is there a simple example that we can define a robot model with friction_loss, damping, and armature on each motor?

**Comment by pwensing** [comment]
Hi there, 

The rotor model in this package treats the rigid-body dynamics of the rotor in their full effect but doesn't address friction. 

**Conventional approximation:** If the rotor rotates about its z-axis, and you have a gear ratio N, then the `armature` term in mujoco would be the reflected inertia $I_{zz} N^2$. The resulting algorithms that approximate the rotor in this way give rise to the same dynamics as if you added a term $\frac{1}{2} N^2  I_{zz} \dot{q}^2$ to the Lagrangian to approximate the effects of the rotor.

**Full treatment:** The treatment of the rotors in the package here addresses the full dynamic effects of the rotors. In a Lagrangian formalism, this would amount to adding kinetic energy $\frac{1}{2} v_{\rm rotor} ^T I_{\rm rotor} v_{\rm rotor}$ (all quantities being spatial ones) and corresponding potential energies. The approximation via the armature reflected inertia accounts for the most dominant effects of the rotor, but misses some other ones such as gyroscopic effects that can become larger with high gap radius motors. 

The RNEA with rotors (matching the algorithm in spatial_v2) is nicely discussed in Modern Robotics. However, this treatment is a special case of a more general class of so-called constraint-embedding algorithms that Jain introduced originally, and that we've been exploring in some recent work [here](https://arxiv.org/abs/2311.13732v2).

I hope that helps! Feel free to let me know if you have any follow-ups.

Best,
-Pat

**Comment by Cfather** [comment]
Thank you for your nice explanations!
