### ISSUE TITLE
Large Values For Regrouping Inertial Parameters

### ISSUE THREAD

**Issue by Cfather** [ROAM-Lab-ND/spatial_v2_extended#17]
Hi, I was trying to run RPNA_URDF_Example.m. I found super large coefficients in some of the regrouped parameters:

Regrouped parameter mcy2 <= **2.8869e+16***Ixy6 - 1.3214e-04*Iyy6 - 0.3160*m3 - 0.3160*m4 - 0.3160*m5 - 1.0233e-06*m7 + mcy2 - mcz3 + 0.3014*mcz6 + **2.5404e+15***mcz7
Regrouped parameter Ixx2 <= Ixx2 - **9.7443e+15***Ixy6 - Iyy2 + Iyy3 + 4.4603e-05*Iyy6 + 0.0999*m3 + 0.1067*m4 + 0.1067*m5 + 3.4541e-07*m7 + 0.6320*mcz3 - 0.1017*mcz6 - **8.5750e+14***mcz7
Regrouped parameter Izz2 <= Iyy3 - **9.7443e+15***Ixy6 + 4.4603e-05*Iyy6 + Izz2 + 0.0999*m3 + 0.1067*m4 + 0.1067*m5 + 3.4541e-07*m7 + 0.6320*mcz3 - 0.1017*mcz6 - **8.5750e+14***mcz7
...

I wonder if there are any methods to improve the numerical stability.

**Comment by pwensing** [comment]
That's no good! I presume you are running it unmodified off of `main`? 

My output is as below with `Identifiable Dimension 43`:
```
Regrouped parameter Izz1 <= Iyy2 + Izz1
Regrouped parameter mcx2 <= mcx2
Regrouped parameter mcy2 <= mcy2 - 0.3160*m4 - 0.3160*m5 - 0.3160*m6 - 0.3160*m7 - 0.3160*m3 - mcz3
Regrouped parameter Ixx2 <= Ixx2 - Iyy2 + Iyy3 + 0.0999*m3 + 0.1067*m4 + 0.1067*m5 + 0.1067*m6 + 0.1067*m7 + 0.6320*mcz3
Regrouped parameter Izz2 <= Iyy3 + Izz2 + 0.0999*m3 + 0.1067*m4 + 0.1067*m5 + 0.1067*m6 + 0.1067*m7 + 0.6320*mcz3
Regrouped parameter Iyz2 <= Iyz2
Regrouped parameter Ixz2 <= Ixz2
Regrouped parameter Ixy2 <= Ixy2
Regrouped parameter mcx3 <= 0.0825*m4 + 0.0825*m5 + 0.0825*m6 + 0.0825*m7 + mcx3
Regrouped parameter mcy3 <= mcy3 - mcz4
Regrouped parameter Ixx3 <= Ixx3 - Iyy3 + Iyy4 - 0.0068*m4
Regrouped parameter Izz3 <= Iyy4 + Izz3 + 0.0068*m4 + 0.0136*m5 + 0.0136*m6 + 0.0136*m7
Regrouped parameter Iyz3 <= Iyz3
Regrouped parameter Ixz3 <= Ixz3
Regrouped parameter Ixy3 <= Ixy3 + 0.0825*mcz4
Regrouped parameter mcx4 <= mcx4 - 0.0825*m6 - 0.0825*m7 - 0.0825*m5
Regrouped parameter mcy4 <= 0.3840*m5 + 0.3840*m6 + 0.3840*m7 + mcy4 + mcz5
Regrouped parameter Ixx4 <= Ixx4 - Iyy4 + Iyy5 + 0.1406*m5 + 0.1406*m6 + 0.1406*m7 + 0.7680*mcz5
Regrouped parameter Izz4 <= Iyy5 + Izz4 + 0.1543*m5 + 0.1543*m6 + 0.1543*m7 + 0.7680*mcz5
Regrouped parameter Iyz4 <= Iyz4
Regrouped parameter Ixz4 <= Ixz4
Regrouped parameter Ixy4 <= Ixy4 + 0.0317*m5 + 0.0317*m6 + 0.0317*m7 + 0.0825*mcz5
Regrouped parameter mcx5 <= mcx5
Regrouped parameter mcy5 <= mcy5 - mcz6
Regrouped parameter Ixx5 <= Ixx5 - Iyy5 + Iyy6 + 0.0077*m7
Regrouped parameter Izz5 <= Iyy6 + Izz5 + 0.0077*m7
Regrouped parameter Iyz5 <= Iyz5
Regrouped parameter Ixz5 <= Ixz5
Regrouped parameter Ixy5 <= Ixy5
Regrouped parameter mcx6 <= 0.0880*m7 + mcx6
Regrouped parameter mcy6 <= mcy6 - mcz7
Regrouped parameter Ixx6 <= Ixx6 - Iyy6 + Iyy7 - 0.0077*m7
Regrouped parameter Izz6 <= Iyy7 + Izz6 + 0.0077*m7
Regrouped parameter Iyz6 <= Iyz6
Regrouped parameter Ixz6 <= Ixz6
Regrouped parameter Ixy6 <= Ixy6 + 0.0880*mcz7
Regrouped parameter mcx7 <= mcx7
Regrouped parameter mcy7 <= mcy7
Regrouped parameter Ixx7 <= Ixx7 - Iyy7
Regrouped parameter Izz7 <= Izz7
Regrouped parameter Iyz7 <= Iyz7
Regrouped parameter Ixz7 <= Ixz7
Regrouped parameter Ixy7 <= Ixy7
```

Internally, the method calculates the range of a bunch of controllability matrices, and small numerical issues can creep in for sure. The system-level regrouping calculations with `rref` are another potential source. 

Can you try adjusting some of the thresholds discussed [here](https://github.com/ROAM-Lab-ND/spatial_v2_extended/issues/11#issuecomment-2304619393) to see if any of those address the issue? If so, we can PR in those adjustments, and I'll double-check that they also work with the examples on my side with the earlier MATLAB version.

I suspect this should be a quick fix! If none of those fix it for you, I'll have to download the new Matlab version, which will unfortunately slow things down.

**Comment by Cfather** [comment]
This might be a false alarm. I tried to pull the original repo and run the same example on another computer (Windows + Matlab R2024b). The results are reasonable. I will dig into it and see what is going on.

Another question that is no related to this issue is actually a feature request. So the matrix `Perp_Basis` gives us the map from the original parameters to the regrouped parameters. I wonder how to do the opposite, in other words, how we can recover the original parameters using the regrouped parameters and the dependent parameters.

And thanks a lot for your quick response.

**Comment by pwensing** [comment]
I'll stay tuned then!

Regarding recovering the full parameters, there are some papers on that problem -- here an insertion point into that literature: doi: [10.1109/ICRA.2016.7487356](http://dx.doi.org/10.1109/ICRA.2016.7487356).

Fundamentally, however, ANY parameters that map onto the regrouped ones are going to give the exact same dynamics. The best example of that, I think, is one originally from Gunter Niemeyer and Jean-Jacques Slotine that we used in our recent paper https://arxiv.org/pdf/1711.03896 (see section 3.2) regarding a revolute joint. If you have a revolute joint, you can take any mass along the axis and "assign" it to either the link before or after the joint. Depending on how you make that assignment, it changes the inertial parameters, and does so in a way that is indistinguishable to the physics. 

In this regard, trying to reconstruct the full parameters from the base ones is sort of an ill-posed problem from the start. If you just want some numbers for all the parameters, you can set all the non-base parameters to zero, and you're golden (or you could do a psuedoinverse). If you want to make sure the parameters are physically consistent, then I think that rules out working with base parameters, and you need to work with the full set from the get-go. [If there were a way to enforce physical consistency of the base parameters directly, that would be an amazing result, but not one that I'm holding my breath for.]

**Comment by Cfather** [comment]
Hi, @pwensing ,

I have double-checked. Unfortunately, I get large values on both Matlab R2022b and R2024b in my Ubuntu system. I was using the original repository. And on different versions of Matlab, the behavior is also different. I think this might be related to the thresholds and the Matlab internal functions.

I have done a really naive change at line 67 in [ComputeBases.m](https://github.com/ROAM-Lab-ND/spatial_v2_extended/blob/main/v3/identifiability/Algorithms/ComputeBases.m#L67). I changed
```
NN = CleanMat( rref(N{i})' );
```
to 
```
NN = rref(CleanMat( N{i} ))';
```
And then I can get exactly the same regrouping results as you have posted.
Would this be a more robust option to clean the matrices before putting them in `rref`?

And thank you so much for your detailed explanation of recovering the full parameters. My motivation is mainly system identification + physical consistency. In [this paper](https://ieeexplore.ieee.org/abstract/document/9097291), the authors treat both regrouped parameters and dependent parameters as decision variables so that they can recover the full parameters and formulate LMI constraints on them.

**Comment by pwensing** [comment]
Thanks for finding a solution that works on your end! I suppose that a more robust solution yet would be to clean the results before and after the `rref` :) I just pushed this change to `main`. Can you please pull down and see if that fixes the issue for you?

**Comment by Cfather** [comment]
Thank you so much! This has fixed my issue!

**Comment by Cfather** [comment]
> I'll stay tuned then!
> 
> Regarding recovering the full parameters, there are some papers on that problem -- here an insertion point into that literature: doi: [10.1109/ICRA.2016.7487356](http://dx.doi.org/10.1109/ICRA.2016.7487356).
> 
> Fundamentally, however, ANY parameters that map onto the regrouped ones are going to give the exact same dynamics. The best example of that, I think, is one originally from Gunter Niemeyer and Jean-Jacques Slotine that we used in our recent paper https://arxiv.org/pdf/1711.03896 (see section 3.2) regarding a revolute joint. If you have a revolute joint, you can take any mass along the axis and "assign" it to either the link before or after the joint. Depending on how you make that assignment, it changes the inertial parameters, and does so in a way that is indistinguishable to the physics.
> 
> In this regard, trying to reconstruct the full parameters from the base ones is sort of an ill-posed problem from the start. If you just want some numbers for all the parameters, you can set all the non-base parameters to zero, and you're golden (or you could do a psuedoinverse). If you want to make sure the parameters are physically consistent, then I think that rules out working with base parameters, and you need to work with the full set from the get-go. [If there were a way to enforce physical consistency of the base parameters directly, that would be an amazing result, but not one that I'm holding my breath for.]

Hi, @pwensing ,

Thank you for your help on this issue! Regarding your comment at the end, I do have a follow-up question after some research:

In the context of system identification for robotic systems, it seems like for a robotics system with some certain level of complexity (not the 2 dof arms that people used in sysid papers in the 90's), the inertial parameters may not be unique to generate the same dynamics (given a bunch of data that we collect from the experiment)? 

So essentially the base parameters that minimize the least square problem may not ensure the physical consistency. On the opposite, there could be multiple physical consistent full parameters that reach the local minimum of the constrained least square problem since the least square problem is essentially rank deficient due to the existence of dependent parameters (inertial parameters that can be regrouped). 

This effect could lead to even weirder results on the real-world data, given all the sensor noise or motor friction or whatever. That's why people add a regularization term in the cost function to make sure the results are not crazy ((25) in your [previous paper](https://ieeexplore.ieee.org/abstract/document/7987066)). 

Does this argument make sense? I appreciate your response in advance!
